backend:
  name: git-gateway
  repo: TUO_UTENTE/sito-bio
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "config"
    label: "Bacheca"
    delete: false
    editor:
      preview: false
    files:
      - name: "annunci_file"
        label: "Lista Annunci"
        file: "content/bacheca.json"
        fields:
          - name: annunci
            label: Annunci
            widget: list
            fields:
              - {label: "Titolo", name: "title", widget: "string"}
              - {label: "Data", name: "date", widget: "datetime"}
              - {label: "Testo", name: "body", widget: "text"}
